service: pizza-boom

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    PREFIX_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  logs:
    restApi: true
    httpApi: true
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - '${opt:region, self:provider.region}'
              - '.amazonaws.com/'
              - Ref: PizzaBoomUserPool
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: arn:aws:dynamodb:*:*:table/${self:custom.config.PREFIX_TABLE}-${self:provider.stage}-users

package:
  individually: false
  exclude:
    - .git/**
    - .cache/**
    - venv/**
    - node_modules/**
    - .serverless/**

custom:
  config: ${file(settings_default.yml)}
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: pizza_boom/handler.hello

resources:
  Resources:
    DynamoPizzaBoomUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.PREFIX_TABLE}-${self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    HttpApi:
      DependsOn: PizzaBoomUserPool
    PizzaBoomUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
            TemporaryPasswordValidityDays: 14
        Schema:
          - Name: email
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: true
          - Name: username
            Required: false
            DeveloperOnlyAttribute: false
            Mutable: true
            AttributeDataType: String
          - Name: dynamo_user_id
            Required: false
            DeveloperOnlyAttribute: false
            Mutable: true
            AttributeDataType: String
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: PizzaBoomUserPool
        Domain: "${self:provider.stage}-users-${self:service}"